# Generated by Django 3.1.4 on 2021-05-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('physics', 'Physics'), ('math', 'Maths'), ('C', 'C Programming'), ('IIT', 'IIT'), ('DL', 'Digital Logic')], max_length=50)),
                ('link', models.CharField(max_length=500)),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
