# Generated by Django 3.1.4 on 2021-05-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
